<?php

namespace uuf6429\ExpressionLanguage;

use Symfony\Component\ExpressionLanguage\Expression as SymfonyExpression;
use Symfony\Component\ExpressionLanguage\ExpressionLanguage as SymfonyExpressionLanguage;
use Symfony\Component\ExpressionLanguage\ParsedExpression as SymfonyParsedExpression;

/**
 * @codeCoverageIgnore
 */
ClassBuilder::create()
    ->import(SymfonyExpression::class)
    ->import(SymfonyParsedExpression::class)
    ->class(ExpressionLanguageWithTplStr::class)
    ->extend(SymfonyExpressionLanguage::class)
    ->use(TemplateStringTranslatorTrait::class)
    ->override(
        'compile',
        'return parent::compile($this->convertExpression($expression), $names);'
    )
    ->override(
        'evaluate',
        'return parent::evaluate($this->convertExpression($expression), $values);'
    )
    ->override(
        'parse',
        'return parent::parse($this->convertExpression($expression), $names);'
    )
    ->override(
        'lint',
        'parent::lint($this->convertExpression($expression), $names);'
    )
    ->createClass();

/**
 * The class definition below will probably never be executed since the real one is generated by
 * the ClassBuilder above. However, the code below is still useful to enable IDE autocompletion.
 */
if (!class_exists(ExpressionLanguageWithTplStr::class)) {
    class ExpressionLanguageWithTplStr extends SymfonyExpressionLanguage
    {
        use TemplateStringTranslatorTrait;
    }
}
