name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '7.0'
            phpunit: '6'
            symfony: '3'
          - php: '7.1'
            phpunit: '7'
            symfony: '4'
          - php: '7.2'
            phpunit: '8'
            symfony: '5'
          - php: '7.3'
            phpunit: '9'
            symfony: '5'
          - php: '7.4'
            phpunit: '9'
            symfony: '5'
          - php: '8.0'
            phpunit: '9'
            symfony: '6'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Set up PHP
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          version: 2.2
          php_extensions: xdebug
          command: require
          only_args: symfony/expression-language:~${{ matrix.symfony }}

      - name: Run tests
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          version: 2.2
          php_extensions: xdebug
          command: run-tests
          only_args: -- --configuration phpunit${{ matrix.phpunit }}.xml.dist

      - name: Upload to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
